### ISSUE TITLE
Nothing displayed - Yahoo API breaking contract change

### ISSUE THREAD

**Issue by clauseggers** [achannarasappa/ticker#247]
When I open ticker I get no stocks listed. Same as in #246 so perhaps they are related.
I’m on version 4.5.6.
I tried opening without the config file, but got same result.
I can run something like `curl https://query1.finance.yahoo.com/v6/finance/quote\?symbols\=AAPL,GOOG,F | jq` and get good output.

Running on MacOS 13.3.1 (a), installed with Ticker was installed with Homebrew.

**Comment by hchr** [comment]
v7 strikes again it seems
curl https://query1.finance.yahoo.com/v7/finance/quote?symbols=tsla
{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}13:14

**Comment by MattyRad** [comment]
Rebuilding ticker after search/replacing `v7` with `v6` seems to fix the issue.

Is there interest in making the yahoo API version configurable?

**Comment by ChangheeOh** [comment]
Same issue.
It seems to be related to macOS latest update.

- OS: 
> ProductName:		macOS
> ProductVersion:		13.3.1

- Ticker version: 4.5.6

**Comment by sarcasticadmin** [comment]
Its broken for me on linux too. No recent OS updates have been applied for me:

```
$ ticker -v
ticker version v4.5.5
```

I suspect its a similar outage to a few weeks ago: https://github.com/achannarasappa/ticker/issues/246

**Comment by achannarasappa** [comment]
Thanks for all the reports! I've created a new release to use the v6 Yahoo API which should fix it but I'll leave this open for a bit to confirm

**Comment by ajgringo619** [comment]
Working as advertised here - thanks for the quick fix!

**Comment by jfbourdeau** [comment]
> Thanks for all the reports! I've created a new release to use the v6 Yahoo API which should fix it but I'll leave this open for a bit to confirm

Still do not work for me on linux, Ticker 4.5.6.  What should I do ?

**Comment by vvidic** [comment]
Probably the same problem described here:

https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python

**Comment by achannarasappa** [comment]
Thanks for reporting this - I can replicate the issue but there is no simple workaround as before so it may take some time to fix this issue.

@vvidic thanks for sharing the above link. I was not able fix the issue by following the steps listed in the link but I'll keep searching to see if someone else has found a workaround.

**Comment by achannarasappa** [comment]
I've made an update that should restore functionality with v4.5.13. I'll close this issue for now but please re-open if this happens again.

---

For those interested, there are three differences with the v7 Yahoo API in the latest breaking change:
1. API calls must have the `A3` cookie set
    a. Sessions expire after about 6 hours
    b. Cookies can be retrieved by visiting the Yahoo Finance homepage ([example](https://github.com/achannarasappa/ticker/blob/master/internal/quote/yahoo/client/client.go#L60))
2. API calls must have the URL query parameter `crumb` set
    a. "crumbs" can be retrieved by requesting `GET https://query2.finance.yahoo.com/v1/test/getcrumb` ([example](https://github.com/achannarasappa/ticker/blob/master/internal/quote/yahoo/client/client.go#L78))
3. API contract for the response from `GET v7/finance/quote` has changed for several fields to include both raw and formatted values ([example](https://github.com/achannarasappa/ticker/blob/master/internal/quote/yahoo/quote_contract_test.go#L47))

**Comment by clauseggers** [comment]
Thank you @achannarasappa but I can’t get past executing the app. When I press return I just get the cursor moved to the next line, where it is then stuck seemingly doing nothing. In some terminal emulators it blinks a few times before going solid.

**Comment by hchr** [comment]
> Thank you @achannarasappa but I can’t get past executing the app. When I press return I just get the cursor moved to the next line, where it is then stuck seemingly doing nothing. In some terminal emulators it blinks a few times before going solid.

I get the same here on Arch
ticker -v
ticker version v4.5.13

**Comment by jfbourdeau** [comment]
Tks for the last update. Everything is working again. JF MTL Canada

**Comment by achannarasappa** [comment]
Looks like there's still an issue but it does not impact everyone. It could be region or machine specific so for those that have issue, would you mind sharing country and machine details to help pinpoint the issue?

**Comment by clauseggers** [comment]
I’m on MacOS latest, installed `ticker` with Homebrew, and I’m located in the Netherlands.

**Comment by 097115** [comment]
Ubuntu 22.04.2, downloaded the binary from the Releases page, another EU country. Same symptoms as described above.

**Comment by hchr** [comment]
System:
Kernel: 6.3.4-arch1-1
Desktop: KDE Plasma v: 5.27.5
Distro: EndeavourOS
CPU:
model: AMD Ryzen 9 5900HX with Radeon Graphics

Denmark

**Comment by ktpx** [comment]
I implemented the same approach in my own app and it works now.   However it does not work with "finance.yahoo.com" in the initial request to get the cookie, I have to use "fc.yahoo.com".

**Comment by eriknh** [comment]
> 

I just updated via the snap updater on Ubuntu server 22.04 to ticker version 4.5.13 and the app works as expected again. However I did not set any cookies. How is it working without me setting a cookie or specifying the CRUMB value?

Also, can I set these somehow as a variable upon calling the "ticker" command? How would I input my own cookie variables otherwise? 

Thank you for the update @achannarasappa and thank you for the explanations.

**Comment by ktpx** [comment]
> 

You don't have to set anything, the code does it.

**Comment by Cubuss** [comment]
i get nothing using snap ticker version 4.5.13
![image](https://github.com/achannarasappa/ticker/assets/9220880/29ef21b4-0b83-48fe-a6e6-8d2e533e95e9)

**Comment by eriknh** [comment]
> > 
> 
> You don't have to set anything, the code does it.

Thanks @ktpx! Great to know the code does this for us. @achannarasappa amazing development on that CRUMB/COOKIE effort. Would love to know if any of these Yahoo Finance variables gets added to the config file should Yahoo start getting finicky about access.

**Comment by achannarasappa** [comment]
I was able to replicate the issue reported by EU users. On finance.yahoo.com, there is a prompt related to EU data privacy regulations that the user must accept before using the Yahoo Finance. Without accepting this prompt, the required cookie (`A3`) is not set. ticker v4.5.13 does not support this today. Look out for an update here soon that adds support.

**Comment by ktpx** [comment]
> I was able to replicate the issue reported by EU users. On finance.yahoo.com, there is a prompt related to EU data privacy regulations that the user must accept before using the Yahoo Finance. Without accepting this prompt, the required cookie (`A3`) is not set. ticker v4.5.13 does not support this today. Look out for an update here soon that adds support.

Thats probably why fc.yahoo.com works here (im in eu), and not finance.yahoo.com.

**Comment by achannarasappa** [comment]
v4.5.14 has just been released which fixes the quote retrieval issue for EU users. Closing this issue for now but will reopen if there's still any unresolved problems.
