### ISSUE TITLE
RESTY error

### ISSUE THREAD

**Issue by gchan510** [achannarasappa/ticker#299]
**Describe the bug**
The holdings page shows the following error:
`ERROR RESTY json: cannot unmarshal string into Go struct field ResponseQuote.quoteResponse.result.regularMarketDayRange of type yahoo.ResponseFieldString`

**To Reproduce**
Go to holdings page

**Expected behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/ebe5884c-6d05-49ee-9acd-3d30e32258ce)

**Environment (please complete the following information):**
 - OS: Linux
 - Terminal: st, xterm
 - Terminal Version: 
 - Font: (Optional) Roboto Mono for Powerline
 - ticker Version: commit 27c8689
**Additional context**

**Comment by Lucasvo1** [comment]
I've opened a PR for this issue: https://github.com/achannarasappa/ticker/pull/300

**Comment by morph13nd** [comment]
<img width="608" alt="Image" src="https://github.com/user-attachments/assets/847e064f-f563-44d1-b77f-206d568edea7" />

Reporting the same issue here on my test bench.
OS: Windows
Terminal: Warp
Ticker Version: https://github.com/achannarasappa/ticker/releases/tag/v4.8.0

The error messages appear on their own within seconds of each other. Resizing the window has them all clear out. If there was a way to suppress error messages, that would help a lot while a fix is being implemented.

**Comment by achannarasappa** [comment]
v4.8.1 should fix the issue but let me know if it does not and I can re-open the issue

**Comment by morph13nd** [comment]
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/3d0a24a7-3fe9-4969-a729-aa154f45ff2b" />

This is still an issue @achannarasappa 

I love this app though, its fantastic, thank you for it!

**Comment by luckytechnician** [comment]
To be honest, that's another issue. Either you have a DNS based adblocker blocking fc.yahoo.com, or you need to set a user agent in the code (don't know if you are setting one now).
